skypyproject/skypy

- docs/galaxy/index.rst
- skypy/galaxy/morphology.py
- skypy/galaxy/tests/test_morphology.py
Implements the ellipticity distribution of galaxies as a reparameterized beta distribution as presented in [Kacprzak et al. 2019](https://ui.adsabs.harvard.edu/abs/2019arXiv190601018K/abstract). Resolves #29
> Galaxy ellipticity distribution from Kacprzak et al. 2109

- docs/galaxy/index.rst
- skypy/galaxy/size.py
- skypy/galaxy/tests/test_size.py
This module computes the angular size of galaxies from their physical size, as described in [1], [2] and [3]. It addresses issue #6  , previous discussion here #73.
* [1] D. W. Hogg, (1999), astro-ph/9905116.
* [2] J. Herbel, T. Kacprzak, A. Amara, A. Refregier, C.Bruderer and
A. Nicola, JCAP 1708, 035 (2017).
* [3] S. Shen, H.J. Mo, S.D.M. White, M.R. Blanton, G. Kauffmann, W.Voges,
J. Brinkmann, I.Csabai, Mon. Not. Roy. Astron. Soc. 343, 978 (2003).
> Galaxy Sizes

- skypy/power_spectrum/growth.py
The doctest for growth_function_carroll gives different outputs using astropy 3.x and 4.x to within algorithmic precision. Use doctest: +ELLIPSIS to effectively lower the precision required on the test output so that it passes in both cases. Fixes #91.
> Fix growth_function_carroll doctest with astropy 4.x

- skypy/utils/tests/test_random.py
`test_schechter` was failing in an unrelated pull request because it was using an imprecise integration method to calculate the cumulative distribution function. This pull request fixes the problem by using an analytic expression for the Schechter cdf.
> Fix kstest in test_schechter using analytic cdf

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/docs.yaml
- .github/workflows/flake8.yaml
- .github/workflows/tests.yaml
- CONTRIBUTING.md
In preparation for retiring the `develop` branch and making `master` the new default branch, update previous references to the default branch to reflect this change.
> Update references to the default branch

- docs/halo/index.rst
- skypy/halo/mass.py
Documentation for `skypy.halo.mass` was not rendering. Now fixed. See #99.
> Fix halo mass documentation

- skypy/__init__.py
This PR fixes the docstring for the whole package to the top-level `./skypy/init.py`. Partly addresses issue #99
> Docstring for `skypy/init.py`

- docs/conf.py
enables plots from examples to be rendered in the generated docs
> enable plots for examples

- skypy/galaxy/ellipticity.py
This PR works around an issue with sampling `scipy.stats.truncnorm` in scipy 1.5.0. I suspect this is a bug in scipy, and if fixed, I will remove the workaround again.
> fix random sampling size for scipy 1.5

- skypy/galaxy/redshift.py
- skypy/galaxy/tests/test_redshift.py
Implement the Smail redshift distribution as a simple function that samples redshifts. This removes the dependency on scipy which throws warnings with v1.5+.
> simplified Smail redshift sampling

- skypy/galaxy/luminosity.py
- skypy/galaxy/redshift.py
- skypy/galaxy/tests/test_luminosity.py
- skypy/galaxy/tests/test_redshift.py
- skypy/utils/astronomy.py
Adds an optional `band` parameter to functions working with absolute magnitudes and luminosities. If a standard filter band is given, luminosities are returned in units of solar luminosity for that band.
> absolute magnitude standard band zeropoints

- examples/herbel_galaxies.yaml
Add fixed sersic indices for red and blue galaxies to the Herbel galaxies example. Resolves #28
> Sersic indices for red and blue galaxies

- skypy/halo/mass.py
The halo_mass_sampler doctests require the RNG seed to be fixed so that the same samples are generated every time. However other doctests can modify the RNG seed causing different values to be generated so the tests fail. Hide the outputs of the halo_mass_sampler doctests to prevent this type of failure.
> Hide random outputs in halo_mass_sampler doctest

- .readthedocs.yml
- docs/conf.py
Camb cannot be built on readthedocs because there is no fortran compiler. Instead do not try to build camb and mock it when building the docs. Resolves #220
> Mock camb on readthedocs

- .zenodo.json
Make all SkyPy members "contributors" with type "ProjectMember" in the zenodo config file
> Use ProjectMember type in zenodo config

- .zenodo.json
The `related_identifiers` field in the zenodo config file is probably the cause of an error when creating a new version. See https://github.com/zenodo/zenodo/issues/1667 for a similar case. Removing that field from our config file.
> Remove related_identifiers from zenodo config

- skypy/pipeline/driver.py
- skypy/pipeline/scripts/skypy.py
- skypy/pipeline/tests/test_driver.py
- skypy/pipeline/tests/test_skypy.py
- Make `config` a positional argument instead of a required argument
- Add `-o/--overwrite` command line flag to `skypy` script to overwrite any existing files with the same names as the output files without warning. Resolves #232
> config and overwrite command line arguments for driver script

- skypy/power_spectrum/_growth.py
- skypy/power_spectrum/tests/test_growth.py
This PR makes `skypy.power_spectrum.growth_function` accepts redshift arrays of arbitrary shape.
> make growth_function accept any redshift shape

- skypy/utils/random.py
- skypy/utils/tests/test_random.py
Optionally rescale the outputs of the Schechter sampler by a multiplicative scale factor. If the scale factor is an array a sample is generated for each element of that array.
> Scaled Schechter samples

- skypy/utils/random.py
- skypy/utils/tests/test_random.py
Improves the efficiency of `skypy.utils.random.schechter()` by not computing the special function, and instead cumulatively summing the (simple) PDF. Since the inverse transform sampling with a fixed grid relies on the function being approximately linear on the grid scale, there is no advantage in computing the CDF instead of summing the PDF on the grid scale.
> improved Schechter random sampling

- skypy/pipeline/scripts/skypy.py
- skypy/pipeline/tests/test_skypy.py
Adds a flag to the `skypy` command that outputs the version of the library.
```bash
$ skypy --version
0.1.dev141+g84a818c
```
> flag to show skypy version

- .github/workflows/examples.yaml
This GitHub workflow should update the skypyproject/examples repository every night, mirroring all branches and tags of our library repository.
> mirror examples to repository

- skypy/gravitational_wave/merger_rate.py
- skypy/gravitational_wave/tests/test_merger_rate.py
Do not use `herbel_luminosities` internally in the `merger_rate` module.
> decouple merger_rate from herbel_luminosities

- setup.cfg
- skypy/galaxy/spectrum.py
- skypy/galaxy/tests/test_spectrum.py
Use `specutils.Spectrum1D` to pass spectrum and bandpass to `skypy.galaxy.spectrum.mag_ab`.
> use specutils for spectrum and bandpass definitions

- skypy/halo/tests/test_quenching.py
The mass quenching tests sometimes fail. This PR changes the p-value from 0.05 to 0.01, which is the number most tests use.
[This PR fixes the issue "the test fails". Perhaps one should also investigate whether everything is in order with the test.]
> change mass quenching p-values

- skypy/utils/tests/test_random.py
The tests for `skypy.utils.random.schechter` can fail randomly when the shape parameter `alpha` makes the distribution so steep that the `resolution` is not enough to produce a good sample. This moves the range of `alpha` to where it is less steep so that this should not happen.
> fix schechter random sampling test failures

- docs/galaxy.rst
- examples/abundance_matching.yml
- examples/gravitational_wave_rates.yml
- examples/mccl_galaxies.yml
- skypy/galaxy/__init__.py
- skypy/galaxy/_schechter.py
- skypy/galaxy/luminosity.py
- skypy/galaxy/redshift.py
- skypy/galaxy/tests/test_luminosity.py
- skypy/galaxy/tests/test_redshift.py
- skypy/galaxy/tests/test_schechter.py
This is an attempt to refactor the Schechter luminosity function sampling to use arbitrary models for `phi_star` and `M_star`.
This PR is based on #271 (but does not require it), so it should be merged after.
> refactor Schechter luminosity function sampling

- skypy/galaxy/spectrum.py
- skypy/galaxy/tests/test_spectrum.py
[specutils.Spectrum1D](https://specutils.readthedocs.io/en/stable/api/specutils.Spectrum1D.html#specutils.Spectrum1D) can contain multiple spectra that share the same `spectral_axis`. In this PR `mag_ab` now checks its arguments for multiple spectra and bandpasses and calculates the magnitudes for each spectrum at each redshift in each bandpass.
Note that this function will calculate the magnitude of each spectrum at every redshift. It cannot calculate the magnitude of the spectra each at a unique redshift.
> mag_ab accepts multiple spectra and bandpasses

- CONTRIBUTING.md
- setup.cfg
- skypy/galaxy/tests/test_ellipticity.py
- skypy/galaxy/tests/test_luminosity.py
- skypy/galaxy/tests/test_redshift.py
- skypy/galaxy/tests/test_schechter.py
- skypy/galaxy/tests/test_size.py
- skypy/galaxy/tests/test_spectrum.py
- skypy/galaxy/tests/test_stellar_mass.py
- skypy/position/tests/test_uniform.py
- skypy/utils/tests/test_random.py
Failing random tests are retested automatically. All future random tests must be marked `@pytest.mark.flaky` as appropriate. Ideally, future distribution test cases should contain only a single test so that non-random failures are not retried.
> mark kstests as flaky with 3 reruns

- setup.cfg
Pin pytest to below 6.1 until pytest-dev/pytest-rerunfailures#128 is sorted out.
> pin pytest<6.1

- setup.cfg
A fixed version of pytest-rerunfailures has been released so this reverts the no longer necessary pytest pin from #295.
> Revert "pin pytest<6.1 (#295)"

- skypy/galaxy/spectrum.py
- skypy/galaxy/tests/test_spectrum.py
Remove units from stellar mass input/output because our driver passes Column, not Quantity, to functions:
```
skypy/galaxy/spectrum.py in magnitudes_from_templates(coefficients, templates, bandpass, redshift, resolution, stellar_mass, distance_modulus)
262         M = mag_ab(templates, bandpass, redshift).reshape(M_shape)
263 
--> 264     stellar_mass = 1 if stellar_mass is None else stellar_mass.to_value(units.Msun)
265     distance_modulus = 0 if distance_modulus is None else distance_modulus
266 
AttributeError: 'Column' object has no attribute 'to_value'
```
> remove stellar mass units

- skypy/pipeline/_pipeline.py
- skypy/pipeline/tests/test_pipeline.py
Pipeline now sets `parameters` and `cosmology` before executing all other jobs in the DAG. The DAG is also resolved using the `default_cosmology.set()` context so that all functions decorated with `@uses_default_cosmology` will use the cosmology defined in the config (or the astropy default cosmology if undefined). Note that currently `cosmology` can only depend on values in parameters and not any other variables defined in the config file. Resolves #293
> Use default cosmology context in pipeline

- skypy/pipeline/_pipeline.py
- skypy/pipeline/tests/test_pipeline.py
Since the function lookup from string incurs a massive overhead when running the pipeline repeatedly, the construction is done only when YAML is parsed, and function objects are stored in the config.
Added benefit: We can raise a useful `ImportError` if a function does not exist:
```
ImportError: module 'astropy.modeling.models' has no attribute 'Linear1'
in "examples/mccl_galaxies.yml", line 7, column 13
```
> Pipeline: load functions from string on construction

- skypy/pipeline/__init__.py
- skypy/pipeline/_config.py
- skypy/pipeline/_pipeline.py
- skypy/pipeline/tests/data/bad_function.yml
- skypy/pipeline/tests/data/bad_module.yml
- skypy/pipeline/tests/test_config.py
Separate the config file parser from the Pipeline class. This allows configurations to be read and then modified in a script before constructing a pipeline, which will be necessary for the lightcone mode implementation in #254.
> Config parser

- examples/mccl_galaxies.yml
- skypy/galaxy/size.py
Quick fix to add the `@uses_default_cosmology` decorator to `skypy.galaxy.size.angular_size` and update the galaxies example, now that the cosmology-setting is working.
> galaxy angular size uses default cosmology

- setup.cfg
- skypy/galaxy/_spectrum_loaders.py
Make skypy-data an optional dependency. Provide installation instructions as part of the ModuleNotFoundError exception message where it is required but not installed. Resolves #321.
> Make skypy-data an optional dependency

- docs/pipeline/index.rst
- skypy/pipeline/scripts/skypy.py
Fixes the sphinx error when building the documentation. The cause is that `automodapi` is invoked on the script file, which currently places documentation of all imported symbols there. Fix is to move the script description to the documentation.
I did not fix the outdated documentation itself.
> fix skypy script documentation

- skypy/galaxy/tests/test_spectrum.py
This PR solves #324. A warning was raised when the distance modulus was calculated at redshift 0. These redshifts are excluded now and I added an extra test that a `RuntimeWarning` is raised in this case.
> Warning test_template_spectra calculating distance modulus

- skypy/galaxy/_spectrum_loaders.py
- skypy/galaxy/spectrum.py
- skypy/galaxy/tests/test_spectrum.py
- skypy/utils/tests/test_decorators.py
Skip tests that require `skypy-data` if the package is not available. Closes #326.
Now also does the right thing in each case when specutils is not installed.
> skip tests if requirements for spectrum functions are not met

- skypy/halo/abundance_matching.py
Fix two sphinx warnings caused by the `vale_ostriker` docs, use correct names of functions, and link said functions.
> fix vale_ostriker documentation warnings

- README.rst
New README can be viewed [here](https://github.com/rrjbca/skypy/blob/readme/README.rst). Changes include:
- New CI badges with logos
- Documentation badge links to 'stable' instead of 'latest'
- Remove instructions for how the user can run tests. The tests are intended for our CI. The existing instructions do not specify installing the testing dependencies and so were incomplete anyway.
- Remove `help(skypy)` from the instructions for importing skypy
- Remove imposter syndrome disclaimer
> Update Readme badges and instructions

- skypy/pipeline/_config.py
- skypy/pipeline/tests/data/quantities.yml
- skypy/pipeline/tests/test_config.py
Construct quantities in config files either using the explicit `!quantity` tag or via auto-matching of entries of the form `<number> <string>`. Closes #315.
> simple construction of quantities in config files

- .zenodo.json
- docs/conf.py
Implementing something like astropy/package-template#495 will make the python [module index ](https://skypy.readthedocs.io/en/latest/py-modindex.html) more easily searchable.
Signed-off-by: Nathaniel Starkman <nstarkman@protonmail.com>
Fixes #348
> Flatten python module index in docs

- docs/pipeline/examples/lightcone.yml
- examples/gravitational_wave_rates.yml
- examples/mccl_galaxies.yml
- skypy/galaxy/_schechter.py
- skypy/galaxy/redshift.py
- skypy/galaxy/tests/test_redshift.py
- skypy/galaxy/tests/test_schechter.py
This PR solves #309 . `fsky` was changed to `sky_area` which has to be given in sr or deg2 units.
> Changing fsky to sky_area

- setup.cfg
- skypy/galaxy/_spectrum_loaders.py
- skypy/pipeline/_pipeline.py
- tox.ini
Drop support for Astropy 3.x:
- Remove outdated API support for `download_file` and `add_columns`
- Update oldest and latest versions to 4.0.x and 4.1.x respectively
Resolves #350 and supersedes #349
> Drop support for Astropy 3.x

- docs/position/examples/uniform_in_pixel.yml
- docs/position/index.rst
- setup.cfg
- skypy/position/__init__.py
- skypy/position/_uniform.py
- skypy/position/tests/test_healpy.py
Adds the `uniform_in_pixel` function to uniformly sample positions over an individual HEALPix pixel.
> sample positions uniformly over HEALPix pixel

- skypy/pipeline/_pipeline.py
- skypy/pipeline/tests/test_pipeline.py
`Pipeline.__getitem__` currently retrieves column data as an `astropy.table.Column` object. This is problematic as many of our functions are written to expect `astropy.units.Quantity` objects as arguments but the `Column` class doesn't support all of the same methods of the `Quantity` class e.g. `to_value`. This pull request modifies `Pipeline.__getitem__` to return column data as an `astropy.units.Quantity` object. Resolves #355.
> Pipeline.__getitem__ returns column data as a Quantity or ndarray

- skypy/power_spectrum/_eisenstein_hu.py
- skypy/power_spectrum/_growth.py
- skypy/power_spectrum/tests/test_eisenstein_hu.py
- skypy/power_spectrum/tests/test_growth.py
The astropy default cosmology will change from `Planck15` to `Planck18` in v4.2. This pull request updates all tests currently using the cosmology returned by `default_cosmology.get()` to compute and compare values to use `Planck15` explicitly.  Resolves #366
> Explicitly use Planck15 cosmology in tests

- .readthedocs.yml
notify us of documentation warnings by failing the ReadTheDocs build
> fail on warnings for RTD sphinx build

- skypy/pipeline/_config.py
- skypy/pipeline/_pipeline.py
- skypy/pipeline/tests/test_config.py
- skypy/pipeline/tests/test_lightcone.py
- skypy/pipeline/tests/test_pipeline.py
Standardise the definition of a function in the pipeline class as a tuple `(function, args, kwargs)` that has three elements: a callable `function`, a list `args`, and a dict `kwargs`. The function call is then always `function(*args, **kwargs)`.
> pipeline: functions are (function, args, kwargs)

- skypy/pipeline/_pipeline.py
- skypy/pipeline/tests/test_pipeline.py
Instead of overriding `astropy.cosmology.default_cosmology`, this PR implements a system by which a `cosmology` argument of a function is set to `$cosmology` if the argument is not set. This happens statically when the pipeline is first constructed and should not add any overhead to the execution. The mechanism is easily extended to similar situations in the future.
> pipeline: do not use default_cosmology

- docs/pipeline/examples/lightcone.yml
- docs/utils/index.rst
- examples/abundance_matching.yml
- skypy/galaxy/_schechter.py
- skypy/galaxy/luminosity.py
- skypy/galaxy/redshift.py
- skypy/galaxy/size.py
- skypy/galaxy/tests/test_luminosity.py
- skypy/galaxy/tests/test_schechter.py
- skypy/halo/abundance_matching.py
- skypy/halo/tests/test_abundance_matching.py
- skypy/utils/__init__.py
- skypy/utils/_decorators.py
- skypy/utils/tests/test_decorators.py
After #371, the `cosmology` variable can now be automatically passed to functions by the `Pipeline` class. The `uses_default_cosmology` decorator is therefore no longer required and can be removed.
> Remove uses_default_cosmology decorator

- setup.cfg
Install classy from PyPI instead of grabbing it from GitHub. Note that currently our CLASS tests fail with `classy==2.9.*` so here we pin to version `classy==2.8.*` in setup.cfg with the intention of refactoring the tests in the future for compatibility with different versions.
> use classy from pip for testing

- setup.cfg
- skypy/galaxy/_spectrum_loaders.py
- skypy/galaxy/spectrum.py
- skypy/galaxy/tests/test_spectrum.py
- skypy/utils/tests/test_decorators.py
This PR solves issue #361. 
In order to add the SDSS filters, we found the `speclite` package which includes multiple filter response curves. 
The advantages of this package is that we don’t have to worry about anything related to licenses and keeping the data up-to-date.
Furthermore, it includes a function where you can create your own filter responds objects. This can be also integrated in the future.
> Access filter responses with speclite package

- README.rst
- setup.cfg
- skypy/galaxy/spectrum.py
- skypy/galaxy/tests/test_spectrum.py
- skypy/utils/tests/test_decorators.py
After #368 and #379 data for optical filters and template spectra are handled without using the [skypyproject/skypy-data](https://github.com/skypyproject/skypy-data) repository and we can therefore drop it as a dependency.
> Drop skypy-data dependency

- setup.cfg
Speclite versions 0.9 and 0.10 fail to install using pip with the same error:
```
TypeError: generate_version_py() missing 2 required positional arguments: 'packagename' and 'version'
```
and using version 0.8 raised a `DeprecationWarning` in our unit tests:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
class FilterSequence(collections.Sequence):
```
This pull request therefore updates the minimum required version of speclite to 0.11.
> Require speclite version 0.11 or later

- skypy/galaxy/size.py
Attempted to address issue https://github.com/skypyproject/skypy/issues/390 by putting underscores after all the references.
> Fix reference links in galaxy.size docstrings

- docs/galaxy.rst
- skypy/galaxy/spectrum.py
The link to `kcorrect` did not show up. It should now.
> build docs for all galaxy.spectrum objects

- .github/workflows/tests.yaml
Set `fetch-depth: 0` when configuring `actions/checkout@v2` to ensure commit SHAs are detectable. 
Previous error message during "Upload coverage to codecov" step:
`Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0`
> fetch-depth zero

- skypy/galaxies/stellar_mass.py
- skypy/galaxies/tests/test_import.py
- skypy/galaxies/tests/test_redshift.py
- skypy/galaxies/tests/test_schechter.py
- skypy/galaxies/tests/test_stellar_mass.py
- skypy/pipeline/_pipeline.py
- skypy/pipeline/tests/test_config.py
- skypy/pipeline/tests/test_import.py
- skypy/tests/test_import.py
- skypy/utils/__init__.py
- skypy/utils/_decorators.py
- skypy/utils/tests/test_decorators.py
- skypy/utils/tests/test_import.py
- skypy/utils/tests/test_photometry.py
Fix style throughout the codebase such that `flake8 skypy --max-line-length=100` returns no errors. This will allow us to use `flake8` for our CI checks as in #427
> Fix flake8 code style errors

- .github/workflows/codestyle.yaml
- .github/workflows/tests.yaml
- CONTRIBUTING.rst
- setup.cfg
- tox.ini
Run code style status check using [`flake8`](https://flake8.pycqa.org/en/latest/) in our GitHub tests workflow as implemented in the latest astropy cookiecutter template. Propose that this replaces codeclimate which uses pycodestyle and therefore cannot detect [PyFlake warnings](https://flake8.pycqa.org/en/2.6.0/warnings.html) e.g. `F401 'module' imported but unused`.
> Code style status check using flake8

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/codestyle.yaml
- .github/workflows/compatibility.yaml
- .github/workflows/tests.yaml
- CONTRIBUTING.rst
- README.rst
- docs/conf.py
- docs/install.rst
- skypy/pipeline/_pipeline.py
Update all references to the default branch to `main`. See #433
> Update name of default branch to main

- docs/install.rst
- docs/pipeline/index.rst
- examples/galaxies/plot_photometry.py
- setup.cfg
- skypy/pipeline/_pipeline.py
- skypy/pipeline/scripts/skypy.py
- skypy/pipeline/tests/test_pipeline.py
- skypy/pipeline/tests/test_skypy.py
- The `skypy` command line script and `Pipeline.write` method now take the full name for the output file as an argument. The format of the file is inferred from lists of allowed extensions.
- `Pipeline.write` now writes all tables to a single file. For a FITS file each table is written to a separate named HDU. For a HDF5 file each table is written to a separate path with the format `tables/<table name>`
- Docstrings and unit tests updated to reflect these changes.
> Write all tables to a single FITS/HDF5 file

- docs/arch/adr-03.md
ADR for the sampling of positions on the sky. Direct link to proposal [here](https://github.com/ntessore/skypy/blob/adr-03/docs/arch/adr-03.md).
> ADR 3: Position sampling and patches of the sky

- skypy/utils/photometry.py
- skypy/utils/tests/test_photometry.py
Attempting to call `mag_ab` without the optional dependency `speclite` installed will now correctly raise an `ImportError` instead of a `NameError`. Fixes #436
> BUG: Raise ImportError if optional dependency speclite is not installed

- tox.ini
Set NumPy latest supported version to 1.20. Consistency tests are currently passing using NumPy 1.20.1.
> MAINT: Set NumPy latest supported version to 1.20

- skypy/power_spectrum/_camb.py
- skypy/power_spectrum/tests/test_camb.py
Fixes configuration of the CAMB interpolator redshift grid so that the user can calculate the power spectrum for specifically `redshift = 0.0`. Fixes #438. More generally the exact power spectrum will be calculated if the number of redshifts requested is less than or equal to the CAMB default parameter `nz_step=100`, otherwise the exact power spectrum is interpolated from a grid of `nz_step` redshifts between `np.min(redshift)` and `np.max(redshift)`.
> BUG: Fix configuration of CAMB interpolator redshift grid

- README.rst
See updated README [here](https://github.com/skypyproject/skypy/blob/d63907ac0611e9212c8db3e7ad6405deedd07838/README.rst)
- Add JOSS status badge
- Move status badges to appropriate subsections in the README to reduce clutter
> Update status badges

- skypy/power_spectrum/_eisenstein_hu.py
- skypy/power_spectrum/tests/test_eisenstein_hu.py
The Eisenstein & Hu approximation for the linear matter power spectrum now assumes the input wavenumber vector to be in units of Mpc instead of Mpc/h (See  [ADR-2](https://github.com/skypyproject/skypy/blob/fad2b7624c87efdbbddf23e249480006ad8c224c/docs/arch/adr-02.md))
The overall amplitude was also missing factors of h. This has now been fixed such that multiplying `eisenstein_hu` by the square of `growth_function_carroll` gives a power spectrum that closely matches CAMB and CLASS.
This addresses issue #442
```python
from astropy.cosmology import Planck18
from matplotlib import pyplot as plt
import numpy as np
from skypy.power_spectrum import camb, eisenstein_hu, growth_function_carroll
k = np.logspace(-3, -1, 50)
z, A_s, n_s = 0, 2.2E-9, 0.97
p_camb = camb(k, z, Planck18, A_s, n_s)
p_eh …
```
> BUG: Fixed wavenumber definition and amplitude scaling in Eisenstein & Hu model

- docs/pipeline/index.rst
- skypy/pipeline/__init__.py
- skypy/pipeline/_items.py
- skypy/pipeline/_pipeline.py
- skypy/pipeline/scripts/skypy.py
- skypy/pipeline/tests/data/test_config.yml
- skypy/pipeline/tests/test_config.py
- skypy/pipeline/tests/test_pipeline.py
- skypy/pipeline/tests/test_skypy.py
- Setup logger, stream handler and formatter for skypy command line script
- Set the logging level using a command line argument
- Log any exceptions raised while executing the command line script
- Setup a logger for the skypy.pipeline module
- Log each job and function call in the Pipeline class and when writing the output file
Example log output:
```bash
>>> skypy -v examples/galaxies/sdss_photometry.yml galaxies.fits
2021-03-22 19:48:35,758 [INFO] skypy.pipeline: Setting cosmology
2021-03-22 19:48:35,758 [INFO] skypy.pipeline: Calling get
2021-03-22 19:48:35,758 [INFO] skypy.pipeline: Generating red_galaxies
2021-03-22 19:48:35,758 [INFO] skypy.pipeline: Calling Table
2021-03-22 19:48:35,758 [INFO] skypy.pipeline: Generating blue_galaxies
2021-03-22 19:48:35,758 [INFO] skypy.pipeline: …
```
> ENH: Logging for skypy command line script and Pipeline class

- docs/galaxies.rst
- docs/utils/index.rst
Addresses Issue #444. This PR adds a small description where to find the spectroscopic filter bands available as an input for the functions of the [Photometry module](https://github.com/skypyproject/skypy/blob/main/skypy/utils/photometry.py).
I added a link to the corresponding speclite documentation in the docs of the `Photometry` module.
> DOC: Describe speclite filters in documentation

- examples/galaxies/sdss_photometry.yml
- skypy/pipeline/_config.py
- skypy/pipeline/tests/data/bad_object.yml
- skypy/pipeline/tests/data/test_config.yml
- skypy/pipeline/tests/test_config.py
This is a proposal for an extension to the config syntax that allows objects to be imported directly from external (sub)modules using the `!` tag and providing neither a list of args or a dict of kwargs. (N.B. to call a function without any arguments pass and empty list of args or an empty dict of kwargs). For example this enables:
```yaml
cosmo1: !astropy.cosmology.Planck18 # import the Planck18 object and bind to cosmo1
cosmo2: !astropy.cosmology.default_cosmology.get [] # call default_cosmology.get() and bind to cosmo2
```
Note that as a result of the design, it is no longer possible to call a function with a single argument using a scalar node; the argument must be put into a list:
```yaml
old_syntax: !len 'hello world!' # invalid
new_syntax: !len ['hello world!'] # correctly define …
```
> ENH: Config syntax for importing objects

- CONTRIBUTING.rst
- skypy/galaxies/luminosity.py
- skypy/galaxies/morphology.py
- skypy/galaxies/redshift.py
- skypy/galaxies/spectrum.py
- skypy/utils/random.py
- skypy/utils/special.py
Removes all docstring examples. Currently they only demonstrate trivial call patterns which should be adequately described by the list of parameters in the docstrings for each function. Any more complex examples that are required should probably be added to the examples directory instead where text, plots and code examples can be better used to explain and demonstrate what the function is doing. Docstring examples are also currently run as part of the tests which is unnecessary given that the actual unit tests should all cover the same simple call patterns.
> DOC: Remove docstring examples

- skypy/galaxies/redshift.py
- skypy/utils/random.py
Add warnings to the docstrings for `schechter` and `redshifts_from_comoving_density` highlighting that the user must choose the `resolution` and `redshift` parameters respectively so as to satisfy their own numerical accuracy requirements.
> DOC: Inverse transform sampling accuracy warning

- setup.cfg
As discussed in #482 there is a conflict between speclite 0.13 (latest) and astropy 4.3.x. It is therefore necessary to make astropy 4.2.x our latest supported version until a fix to speclite is released.
> MAINT: Set astropy latest supported version to 4.2

- examples/galaxies/sdss_dered_10deg2.ecsv
In the ecsv file [`examples/galaxies/sdss_dered_10deg2.ecsv`](https://github.com/skypyproject/skypy/blob/main/examples/galaxies/sdss_dered_10deg2.ecsv) change the invalid datatype `int` to `uint16`. Resolves #484
> BUG: Change invalid ecsv datatype from int to uint16

- .readthedocs.yml
- docs/requirements.txt
- pyproject.toml
speclite 0.13 is incompatible with the recent setuptools 58.0.2 release. Fix the version of setuptools used to `setuptools<58.0.2` until the dependency conflict is resolved. Resolves #492
> DEV: setuptools==58.0.0

- README.rst
An incompatibility with the astropy development branch was recently caught by our compatibility workflow but the failure was not noticed or acted on by developers before it was released. This pull request adds a status badge for the compatibility workflow to the README to increase the visibility of failures for developers.
> DOC: Add compatibility workflow badge

- tox.ini
Enable pip to install pre-releases in the tox dev environments. Fixes #490 since the scipy-wheels-server only hosts pre-releases and so there are no *releases* of numpy satisfying scipys dependency on `numpy>=1.17.3`. Setting  `pip_pre=True` allows pip to install the `numpy==1.22.0.dev` *pre-release* resolving the dependency conflict. See compatibility workflow logs on the rrjbca/skypy fork e.g. [HERE](https://github.com/rrjbca/skypy/runs/3531344737?check_suite_focus=true) demonstrating successful execution of the compatibility workflow in the `py39-test-dev` environment.
> DEV: Enable pip to install pre-releases in the tox dev environments

- skypy/pipeline/tests/test_pipeline.py
- skypy/pipeline/tests/test_skypy.py
Use pytest `tmp_path` fixture in unit tests. Creates a temporary directory where temporary files can be written and handles cleanup automatically. Resolves #466
> TST: Use tmp_path fixture for temporary files in unit tests

- setup.cfg
- tox.ini
speclite 0.14 will contain a fix that allows us to support astropy 4.3.x. Resolves #482
> BLD: Set astropy latest supported version to 4.3 and speclite minversion to 0.14

- .readthedocs.yml
- docs/requirements.txt
This reverts PR #493. To be merged after a new speclite release fixing the incompatibility with setuptools>=58.0.2
> REV: restore setuptools to latest version on readthedocs

- setup.cfg
Reverts #500. To be merged after a new matplotlib release fixing the incompatibility with pyparsing 3.x
> REV: restore pyparsing to latest version for doc builds

- tox.ini
Set astropy latest supported version to 5.0
> BLD: Set astropy latest supported version to 5.0

- tox.ini
Set numpy latest supported version to 1.22
> BLD: Set numpy latest supported version to 1.22

- .github/workflows/tests.yaml
- CONTRIBUTING.rst
- docs/install.rst
- setup.cfg
- tox.ini
Python 3.6 is end-of-life and future releases should not support it. This PR sets the oldest supported version of python to 3.7
> BLD: Set python oldest supported version to 3.7

- README.rst
The link to the code of conduct was broken in the readme.
> DOC: Fix code of conduct link

- examples/galaxies/plot_schechter.py
Closes #509. Changed the y-label in the example of the Schechter Luminosity function from `log(\Phi)` to `\Phi`.
> BUG: Changed y-label in luminosity function example

- skypy/power_spectrum/_halofit.py
Add __name__ to halofit partial models (halofit_smith, halofit_takahashi, halofit_bird) as this is required for pipeline logging. Partial fix to documentation build error in the power spectrum example plot.
~N.b. the readthedocs build error `AttributeError: 'function' object has no attribute 'Om0'` is a separate issue addressed by #527. This PR should be merged after that one.~
> Add __name__ to Halofit partial models for logging

- skypy/utils/tests/test_photometry.py
The compatibility workflow is currently failing, see [HERE](https://github.com/skypyproject/skypy/runs/6438716098?check_suite_focus=true#step:6:116)
The development version of numpy appears to cause a small numerical change in the calculation of the Rykoff photometric error. This causes the unit test to fail because it asserts that the calculated error is exactly equal to the analytic value. This PR changes the test to assert that the calculated error is numerically close to the analytic value.
Compatibility tests are shown to work with this fix [HERE](https://github.com/rrjbca/skypy/actions/runs/2357233927)
> TST: assert photometric error is numerically close to the analytic value

- skypy/utils/tests/test_special.py
The latest astropy development version has deprecated `astropy.tests.helper.raises`. This raises a warning in our compatibility workflow e.g. [HERE](https://github.com/skypyproject/skypy/runs/6438716098?check_suite_focus=true#step:6:150). Following the astropy recommendation, this PR drops `astropy.tests.helper.raises` and uses `pytest.raises` instead.
> TST: Drop deprecated astropy.tests.helper.raises

- skypy/galaxies/spectrum.py
- skypy/galaxies/tests/test_spectrum.py
Adds the `stellar_mass_remain()` function to the kcorrect template class which computes total surviving stellar mass
> ENH: compute kcorrect remaining stellar mass

- skypy/galaxies/__init__.py
- skypy/galaxies/stellar_mass.py
- skypy/galaxies/tests/test_stellar_mass.py
This PR enables `alpha` and `m_star` in `schechter_smf` being functions. Before it was prevented by the `schechter_smf_mass` function. To resolve I added a set of decorators to `schechter_smf_mass`. Closes #523.
Furthermore, I included `schechter_smf` in the docs where they weren't included before. Closes #522.
> BUG: `schechter_smf` callable input and docs

- tox.ini
Set numpy latest supported version to 1.23
> BLD: Set numpy latest supported version to 1.23

- skypy/power_spectrum/_base.py
- skypy/power_spectrum/_camb.py
- skypy/power_spectrum/_classy.py
- skypy/power_spectrum/_eisenstein_hu.py
- skypy/power_spectrum/tests/test_camb.py
- skypy/power_spectrum/tests/test_eisenstein_hu.py
Implements PowerSpectrum (and TabulatedPowerSpectrum) classes to provide a common interface for power spectrum calculations (using interpolation). Also implements EisensteinHu, CAMB and CLASS classes to replace previous raw functions.
N.b. data used when testing CLASS was found to be inaccurate and has been recalculated. However, even the new "correct" data does not match our interpolation method at the previous relative tolerance of 1e-4 so this has been reduced to 1e-3.
> ENH: Power spectrum base classes

- docs/power_spectrum/index.rst
- skypy/power_spectrum/_camb.py
Read the Docs not working with new CAMB function deletions, need to remove reference to the function, changed to class
This will close #557
> MAINT: Documentation for power spectrum

- skypy/power_spectrum/_eisenstein_hu.py
- skypy/power_spectrum/_halofit.py
Added EisensteinHuHalofit class and its corresponding documentation.
Still missing unit tests
Class includes the `model` attribute which selects between three parameter sets for halofit: Bird, Smith and Takahashi.
> ENH: E&Hu halofit class and documentation

- skypy/pipeline/scripts/skypy.py
- skypy/pipeline/tests/test_skypy.py
- skypy/utils/photometry.py
Merging will close #571 .
This simply addresses some test failures on flake8 E275 (missing whitespace after keyword).
> MAINT: flake8 E275 fixes

- tox.ini
Merging will close #586 
Tests currently fail because Tox v4 requires comma separation in passenv, rather than whitespace.
> MAINT: Replaced whitespace in tox config

- tox.ini
Set numpy latest supported version to 1.24
> BLD: Set numpy latest supported version to 1.24

- tox.ini
Set astropy latest supported version to 5.2
> BLD: Set astropy latest supported version to 5.2

- tox.ini
The tox indexserver configuration has been removed. This is causing the compatibility workflow to fail for dev environments which attempt to install numpy and scipy from the scipy-nightly-wheels server. This pull request modifies the tox dev environments to instead set the PIP_INDEX_URL and PIP_EXTRA_INDEX_URL environment variables to scipy-nightly-wheels and PyPI respectively.
I have tested this on a branch where I modified the compatibility workflow to be run on git pushes (rather than a cron schedule):
- Failing before the fix: https://github.com/rrjbca/skypy/actions/runs/4525234641/jobs/7969595361
- Passing with the fix cherry-pick'd: https://github.com/rrjbca/skypy/actions/runs/4525238985/jobs/7969602066
(Note that the passing tests installed numpy==1.25.0.dev0+941.gb35aac2c3 and …
> tox indexserver is deprecated; use PIP_INDEX_URL and PIP_EXTRA_INDEX_URL in dev environments

- tox.ini
Set numpy latest supported version to 1.25
> BLD: Set numpy latest supported version to 1.25

- tox.ini
Set astropy latest supported version to 5.3
> BLD: Set astropy latest supported version to 5.3

- skypy/conftest.py
Update conftest to latest version from [astropy/package-template](https://github.com/astropy/package-template)
Resolves #600
> TST: Use conftest from latest astropy package template

- tox.ini
Set numpy latest supported version to 1.26
> BLD: Set numpy latest supported version to 1.26

- .readthedocs.yml
- skypy/utils/photometry.py
Readthedocs is currently failing for #608 with `Problem in your project's configuration. Invalid configuration option "build.os": os not found`: https://readthedocs.org/projects/skypy/builds/22378505/
This PR updates .readthedocs.yml following the latest version in astropy package-template which configures the build os: https://github.com/astropy/package-template/blob/cookiecutter/%7B%7B%20cookiecutter.package_name%20%7D%7D/.readthedocs.yml
Also fixes two subsequent failures:
- Fixes incorrect underline length in the docstring for `logistic_completeness_function`
- Add graphviz to apt_packages in readthecods configuration
> MAINT: Update .readthedocs.yml to latest version in astropy package-template

- tox.ini
Set astropy latest supported version to 6.0
> BLD: Set astropy latest supported version to 6.0

- .github/workflows/codestyle.yaml
- .github/workflows/compatibility.yaml
- .github/workflows/tests.yaml
The GitHub actions checkout@v2, setup-python@v2 and codecov-action@v1 all raise the warning "uses node12 which is deprecated". This PR upgrades the skypy workflows to use checkout@v4, setup-python@v4 and codecov-action@v3 which uses the compliant node16.
> BLD: Upgrade GitHub actions that use deprecated node12

- tox.ini
Set astropy latest supported version to 6.1
> BLD: Set astropy latest supported version to 6.1

- tox.ini
In scipy 1.14 the `scipy.integrate.cumtrapz` will be deprecated. However the alias `scipy.integrate.cumulative_trapezoid` was not added until scipy 1.6. This pull request increases the oldest supported version of scipy to 1.6.
> BLD: Set scipy oldest supported version to 1.6

- skypy/galaxies/tests/test_stellar_mass.py
- skypy/galaxies/tests/test_velocity_dispersion.py
The alias `scipy.integrate.cumtrapz` is deprecated. Use `scipy.integrate.cumulative_trapezoid` instead.
Depends on #618 incrementing the minimum supported version of scipy to 1.6 (the version when `scipy.integrate.cumulative_trapezoid` was added)
> BUG: Use scipy.integrate.cumulative_trapezoid

- examples/galaxies/plot_schechter.py
- skypy/galaxies/redshift.py
- skypy/galaxies/tests/test_redshift.py
[numpy.trapz is deprecated](https://numpy.org/devdocs/release/2.0.0-notes.html#deprecations); use scipy.integrate.trapezoid instead. Note that in numpy 2.0 the alias [numpy.trapezoid](https://numpy.org/devdocs/reference/generated/numpy.trapezoid.html) was added, but to maintain backwards compatibility with numpy 1.x we follow the suggestion of using the scipy method instead.
> MAINT: numpy.trapz is deprecated; use scipy.integrate.trapezoid

- .github/workflows/codestyle.yaml
- .github/workflows/compatibility.yaml
- .github/workflows/tests.yaml
Upgrade actions/setup-python to version 5 (v4 uses deprecated version of Node.js)
> MAINT: Upgrade to actions/setup-python@v5

- tox.ini
Set numpy oldest supported version to 1.17
> BLD: Set numpy oldest supported version to 1.17

- tox.ini
BLD: Set numpy latest supported version to 2.1
> BLD: Set numpy latest supported version to 2.1

- tox.ini
Set astropy latest supported version to 7.0
> BLD: Set astropy latest supported version to 7.0

- tox.ini
BLD: Set numpy oldest supported version to 1.19; older version are incompatible with the oldest supported version of python (3.9)
> BLD: Set numpy oldest supported version to 1.19

- tox.ini
Set numpy latest supported version to 2.2
> BLD: Set numpy latest supported version to 2.2

- skypy/galaxies/spectrum.py
In Python 3.13 the use of PosixPath objects as context managers is deprecated. Update the use of importlib.resources.files, storing the output to a variable instead.
> MAINT: Don't use importlib.resources.files as a context manager

- .readthedocs.yml
Add explicit sphinx.configuration field which is now required in readthedoc.conf
> MAINT: Add required sphinx.configuration to readthedocs.conf

- skypy/utils/special.py
- skypy/utils/tests/test_special.py
The SkyPy implementation of the upper incomplete gamma function uses `scipy.special.gammasgn` to identify poles of the gamma function. However since SciPy 1.15 the behaviour of that function has changed :
```python
>>> scipy.special.gammasgn([-2, -1, 0])
array([0., 0., 0.])
>>> scipy.special.gammasgn([-2, -1, 0])
array([nan, nan,  1.])
```
This MR introduces a utility function `_is_gamma_pole` that correctly identifies poles of the gamma function using `gammasgn` for all supported versions of SciPy
> MAINT: Utility function to check if a value is a pole of the gamma function

- skypy/_astropy_init.py
Drop astropy TestRunner as it will soon be deprecated
Resolves #648
> MAINT: drop astropy TestRunner (deprecated)

- tox.ini
Set numpy latest supported version to 2.3
> BLD: Set numpy latest supported version to 2.3
