skypyproject/skypy

skypy/halo_sampler.py
Halo sampler based on Sheth & Tormen 1999 formalism (https://arxiv.org/pdf/astro-ph/9901122.pdf) and https://www.slac.stanford.edu/econf/C070730/talks/Wechsler_080207.pdf
It addresses issue #13
=> sampling haloes

skypy/galaxy/luminosity.py, skypy/galaxy/tests/test_luminosity.py, skypy/utils/random.py, skypy/utils/tests/test_random.py
Utility function to sample galaxies from the Schechter function.
- ~It lacks unit tests~ Suggestions for more tests.
- ~Documentation should be improved.~
- Needs #issues to be linked to and a better description
=> Utils random

skypy/halo/mass.py, skypy/halo/tests/test_mass.py
The halo mass function from the Press-Schechter formalism. This pull-request addresses issue #12.
* Press, W. H. and Schechter, P., APJ, (1974).
- It needs more tests (suggestions?)
=> Press-Schechter Mass Function

README.rst
Add badges for GitHub actions and PyPI CI statuses to README
=> Add badges for GitHub actions and PyPI

docs/power_spectrum/index.rst, skypy/power_spectrum/__init__.py, skypy/power_spectrum/_camb.py, skypy/power_spectrum/_eisenstein_hu.py, skypy/power_spectrum/_growth.py, skypy/power_spectrum/_halofit.py, skypy/power_spectrum/tests/test_camb.py, skypy/power_spectrum/tests/test_eisenstein_hu.py, skypy/power_spectrum/tests/test_growth.py, skypy/power_spectrum/tests/test_halofit.py
This is a proposal to flatten the power spectrum hierarchy a little. The number of functions in the current 4 submodules is O(1) so I don't think submodules are really a helpful thing to have. It makes for a nicer logical structure as well I believe.
Please have a look at the documentation to see the new structure.
=> flatten power spectrum hierarchy

skypy/cluster/__init__.py
=> set up cluster directory

README.rst
Added the Zenodo badge with the DOI of the latest release.
=> added Zenodo badge with DOI

docs/cluster/index.rst, docs/index.rst
Add cluster module to documentation index. Part of #154
=> Add cluster module to documentation index

skypy/halo/mass.py
=> fix press_schechter documentation warning

.circleci/config.yml, .github/workflows/docs.yaml, docs/pipeline/index.rst, skypy/pipeline/driver.py
=> fix driver documentation

docs/galaxy.rst, skypy/galaxy/ellipticity.py, skypy/galaxy/tests/test_ellipticity.py
Adds the ellipticity distribution following [Ryden (2004)](https://ui.adsabs.harvard.edu/abs/2004ApJ...601..214R).
=> ellipticity distribution of Ryden (2004)

.github/workflows/compatibility.yaml, .github/workflows/tests.yaml, tox.ini
Tests across a range of python, astropy, numpy, and scipy versions.
=> test matrix

codecov.yml
=> Disable Codecov comments in pull requests

.github/workflows/tests.yaml
Report coverage to codeclimate.
=> report codeclimate coverage

examples/herbel_galaxies.yaml, skypy/galaxy/ellipticity.py
Fixes two easy bugs:
- broken pipeline example after #199.
- scipy `truncnorm` sampling hasn't been fixed in 1.5.1
=> fix minor bugs

skypy/pipeline/driver.py, skypy/pipeline/scripts/skypy.py, skypy/pipeline/tests/data/cosmology_config.yaml, skypy/pipeline/tests/data/test_config.yml, skypy/pipeline/tests/test_driver.py, skypy/pipeline/tests/test_skypy.py
Implements new features for the the SkyPy pipeline driver:
- Generate arbitrary variables from functions
- Initialise tables from functions (resolves #9)
- For each table create a `table.complete` node in the DAG that depends on all of it's columns
- Support dependencies on jobs without having to pass them as keyword arguments
=> Pipeline variables, table initialisation and dependencies

examples/abundance_matching.yml
Simple example matching halos by mass with galaxies by luminosity at fixed redshift. Subhalo populations will be added in a future version.
=> Abundance matching example

examples/gravitational_wave_rates.yml
Simple example calculating the neutron star-neutron star merger rates for a population of galaxies.
=> Simple gravitational wave event rate example

CONTRIBUTING.md
Add a description of the automated status checks run on pull requests and how to interact with them to the contributor guidelines. Resolves #223
=> Add description of status checks to contributor guidelines

skypy/halo/mass.py, skypy/halo/tests/test_mass.py
Fixing errors and typos in halo mass function and tests. This pull request resolves #225.
=> Halo sampler bug

docs/galaxy.rst, docs/halo/index.rst, skypy/galaxy/redshift.py, skypy/galaxy/spectrum.py, skypy/galaxy/stellar_mass.py, skypy/halo/quenching.py
This pull request adds missing functions in the documentation. It resolves #222.
=> Adding missing functions

README.rst
=> Fixing typo in README example

codecov.yml
Disable Codecov annotations in GitHub pull request patches. See [Codecov GitHub Checks](https://docs.codecov.io/docs/github-checks-beta).
=> Disable Codecov annotations

CONTRIBUTING.md
Change a few outdated bits in the guidelines.
=> update contributor guidelines

README.rst
Instructions to clone the [skypyproject/examples](https://github.com/skypyproject/examples) repository
=> Instructions to clone examples repository

skypy/__init__.py, skypy/galaxy/__init__.py, skypy/halo/__init__.py
Import all (science) packages and modules
=> Import packages and modules

README.rst
=> Typo: –- -> --

examples/abundance_matching.yml, examples/gravitational_wave_rates.yml, examples/mccl_galaxies.yml, skypy/pipeline/driver.py, skypy/pipeline/tests/data/test_config.yml, skypy/pipeline/tests/test_driver.py
This PR makes it possible for config files to have functions with arguments that contain functions themselves.
This requires a different syntax `$variable` or `$table.column` for references.
```yaml
mystring: 'hello world'
list_range_len_mystring: !list
- !range
- !len
- $mystring
```
=> config files can have nested function calls

skypy/galaxy/size.py
Do not fix the seed for random sampling in tests. These seem to cause weird results.
=> do not fix seed in tests

skypy/power_spectrum/__init__.py, skypy/power_spectrum/_classy.py
Add classy to linear power spectrum documentation
=> Add classy to linear power spectrum documentation

skypy/halo/tests/test_quenching.py
The quenching tests were not previously marked as flaky because I didn't pay attention.
=> mark quenching tests as flaky

setup.cfg, skypy/galaxy/_spectrum_loaders.py
Use the [skypy-data](https://github.com/skypyproject/data) package to provide spectral data.
=> use skypy-data package for spectral data

skypy/pipeline/_config.py
Create a custom `yaml.SafeLoader` subclass for SkyPy as detailed in yaml/pyyaml#221 to prevent our extensions from interfering with other YAML loaders.
=> custom SkyPy YAML loader subclass

skypy/halo/mass.py
This pull request fixes a small bug in the examples section. Merging will close #311
=> Fix bug in examples section

setup.cfg, skypy/__init__.py, skypy/galaxy/tests/test_luminosity.py, skypy/pipeline/tests/test_pipeline.py, skypy/power_spectrum/tests/test_camb.py, skypy/power_spectrum/tests/test_class.py
Merging this will close #328. ~I have also fixed the deprecated `[pep8]` section in the `setup.cfg`.~
=> fixed pycodestlye errors

docs/pipeline/examples/config.yml, docs/pipeline/examples/lightcone.yml, docs/pipeline/index.rst
Updated pipeline documentation for v0.3 including:
- Description of v0.3 config syntax
- Simplified script that reruns pipeline with updated parameters
- Example using Lightcone class
Resolves #320
=> Update Pipeline documentation for v0.3

docs/halo/examples/halo.yml, docs/halo/index.rst
This PR updates the halo documentation on [readthedocs](https://skypy.readthedocs.io/en/latest/halo/index.html) to add examples and plots. Merging this PR closes #305.
=> Update Halo documentation for v0.3

skypy/power_spectrum/_eisenstein_hu.py, skypy/power_spectrum/tests/test_eisenstein_hu.py
=> Check if Ob0 and Tcmb0 are non-zero for wiggle=T

skypy/__init__.py, skypy/cluster/tests/test_import.py, skypy/galaxy/tests/test_import.py, skypy/gravitational_wave/tests/test_import.py, skypy/halo/tests/test_import.py, skypy/pipeline/tests/test_import.py, skypy/position/tests/test_import.py, skypy/power_spectrum/tests/test_import.py, skypy/supernova/tests/test_import.py, skypy/tests/test_import.py, skypy/utils/__init__.py, skypy/utils/tests/test_import.py
Adds missing submodule imports to modules and tests module import statements.
=> fix and test package imports

skypy/galaxy/spectrum.py, skypy/galaxy/tests/test_spectrum.py
Evaluate the metallicities of galaxies as a linear combination of the metallicities of the kcorrect template spectra from which they are composed. Resolves #150
=> Metallicity from kcorrect templates

skypy/galaxy/spectrum.py, skypy/galaxy/tests/test_spectrum.py
Evaluate the star formation rates of galaxies as a linear combination of the star formation rates of the kcorrect template spectra from which they are composed. Resolves #146
=> Star formation rates from kcorrect templates

.github/workflows/compatibility.yaml, .github/workflows/tests.yaml, tox.ini
updates to scipy v1.6 and astropy v4.2
=> bump dependency versions

licenses/TEMPLATE_LICENCE.rst
Adding a license for the satrapy template package.
=> astropy package template license

examples/galaxies/plot_photometry.py
Fixes two small reference issues in the [current photometry example](https://skypy.readthedocs.io/en/latest/examples/galaxies/plot_photometry.html).
=> fix refs in photometry example

.zenodo.json
update affiliation for 0.4 release
=> affiliation change

.github/workflows/tests.yaml
Trigger GitHub actions to run the unit tests for commits and pull requests on the new module branches.
=> Run unit tests on module branches

examples/galaxies/plot_schechter.py, examples/galaxies/plot_size.py
Use sphinx :download: role to create download links for data files in examples instead of hyperlinks to raw text files in the GitHub repository.
=> Download links for data files in examples

skypy/power_spectrum/tests/test_import.py
Fix flake8 code style errors in power_spectrum module
=> Fix flake8 code style errors in power_spectrum module

skypy/halos/tests/test_import.py
Fix flake8 code style errors in halos module. Requires #430 to be merged first.
=> Fix flake8 code style errors in halos module

.zenodo.json
This PR update's @Lucia-Fonseca 's affiliation in Zenodo.
=> MAINT: Update Lucia affiliation

.zenodo.json
Add Sutieng's details to .zenodo.json
=> MAINT: add SIT's information

README.rst
This PR fixes the link for the Contributing Guidelines in the README.rst file. Merging this PR closes #448 .
=> DOC: Fix contributor guidelines link

skypy/power_spectrum/_camb.py, skypy/power_spectrum/_classy.py, skypy/power_spectrum/_eisenstein_hu.py, skypy/power_spectrum/_growth.py, skypy/power_spectrum/_halofit.py
This PR removes the docstring examples sections. Merging this PR closes #446.
=> DOC: Remove Docstring examples in power_spectrum

.zenodo.json
Update name and affiliation for RPR in Zenodo config file.
=> MAINT: Update Zenodo entry for RPR

.zenodo.json, README.rst
This PR adds information to the README.
- The first paragraph is expanded based on comments received on the JOSS paper to more specifically state the uses of SkyPy.
- The `main_functionalities` documentation page added in response to a JOSS paper comment is linked (see #443)
- The 'Get in Touch' section has been added. This requires the external actions of enabling the Discussions tab and setting up the email address (see #459)
=> DOC: Readme updates

.zenodo.json
This PR updates the members' info in the zenodo json file:
* Add Laura, Arthur and Will info
* Update affiliations
Merging this PR closes #480
=> DOC: zenodo json members update

tox.ini
- Set numpy latest supported version to 1.21
- Set scipy latest supported version to 1.7
=> MAINT: Update numpy and scipy latest supported versions

.github/workflows/compatibility.yaml, .github/workflows/tests.yaml, tox.ini
Set python latest supported version to 3.10
=> BLD: Set python latest supported version to 3.10

tox.ini
Set scipy latest supported version to 1.22
=> BLD: Set scipy latest supported version to 1.8

.zenodo.json
This PR adds Fox's details for Zenodo records.
=> MAINT: Add Zenodo entry for FD

skypy/power_spectrum/__init__.py, skypy/power_spectrum/tests/test_base.py
This PR adds a unit test for the TabulatedPowerSpectrum class in the [skypy.power_spectrum._base](https://github.com/skypyproject/skypy/blob/module/power_spectrum/skypy/power_spectrum/_base.py) module.
=> TST: Adding unit test for TabulatedPowerSpectrum

skypy/power_spectrum/__init__.py, skypy/power_spectrum/_camb.py, skypy/power_spectrum/tests/test_camb.py
Delete extra CAMB function, any associated unit tests and references
Merging this pull request closes #553
=> MAINT: Delete CAMB function

skypy/power_spectrum/_classy.py
This PR adds a docstring for the CLASSY class. Merging this PR closes #561 .
=> DOC: Add doctsring for CLASSY class

tox.ini
Set scipy latest supported version to 1.9
=> BLD: Set scipy latest supported version to 1.9

tox.ini
Set scipy latest supported version to 1.10
=> BLD: Set scipy latest supported version to 1.10

.github/workflows/compatibility.yaml, .github/workflows/tests.yaml, tox.ini
Set python latest supported version to 3.11
=> BLD: Set python latest supported version to 3.11

tox.ini
Set scipy latest supported version to 1.12
=> BLD: Set scipy latest supported version to 1.12

tox.ini
Set scipy latest supported version to 1.13
=> BLD: Set scipy latest supported version to 1.13

tox.ini
Set scipy latest supported version to 1.14
=> BLD: Set scipy latest supported version to 1.14

tox.ini
Set numpy latest supported version to 2.0
=> BLD: Set numpy latest supported version to 2.0

.github/workflows/codestyle.yaml, .github/workflows/tests.yaml
Run tests and codestyle on release branches and tags
=> CI: Run tests and codestyle on release branches and tags

skypy/galaxies/spectrum.py
pkg_resources is deprecated; switch to importlib.resources
=> MAINT: Use importlib.resources

tox.ini
Set scipy latest supported version to 1.15
=> BLD: Set scipy latest supported version to 1.15
